config/routes.rb
BoardEngine::Engine.routes.draw do
	namespace :admin do
		scope "b" do
			resources :boards
			resources :comments
		end

		scope "b/:board_title" do
			resources :articles
		end
	end

	scope "b" do
		resources :boards
		resources :comments
	end
	
	scope "b/:board_title" do
		resources :articles
	end
end

app/models/board_engine/article.rb
# encoding: utf-8

module BoardEngine
  class Article < ActiveRecord::Base
  	# FIXME: engine에서 에디터불러오면 삽입 이미지의 model명을 제대로 못 가져옴
	  include CleditorWithPicture::AssociateWithEditorPicture
  	mount_uploader :attached_picture, ArticlePictureUploader
    attr_accessible :title, :body, :child_picture_ids, :attached_picture

    belongs_to :board
    belongs_to :user
    has_many	 :comments, :as => :commentable, :dependent => :destroy
    
    validates_presence_of :title, :body, :board_id, :user_id
  end
end

app/models/board_engine/board.rb
# encoding: utf-8
module BoardEngine
  class Board < ActiveRecord::Base
    # attr_accessible :title, :board_type
    acts_as_list
    has_many :articles, :dependent => :destroy
    validates_uniqueness_of :title
    validates_presence_of :title, :board_type
    #BOARD_TYPE = {1 => '일반 게시판', 2 => '이미지 게시판'}
  end
end

app/models/board_engine/comment.rb
# encoding: utf-8

module BoardEngine
  class Comment < ActiveRecord::Base
	  belongs_to :user
	  belongs_to :article
	  belongs_to :commentable, :polymorphic => true
	  
	  validates :body, :user_id, :presence => true
	  validates :body, :length => { :maximum => 400 }
  end
end

app/controllers/board_engine/admin/admins_controller.rb
# encoding: utf-8

class BoardEngine::Admin::AdminsController < Admin::AdminsController
	before_filter :is_from_engine

	def is_from_engine
		@is_from_engine = true		
	end	
end

app/controllers/board_engine/admin/articles_controller.rb
# encoding: utf-8

class BoardEngine::Admin::ArticlesController < BoardEngine::Admin::AdminsController
	before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]
	before_filter :find_board

	def index
		@articles = @board.articles.order("created_at DESC").page(params[:page]).per(15)
	end

	def show
		@article = BoardEngine::Article.find params[:id]
	end

	def new
		@article = BoardEngine::Article.new
		@article.board_id = @board.id
	end

	def edit
		@article = @board.articles.find params[:id]
	end

	def create
		@article = @board.articles.build params[:article]
		@article.user_id = current_user.id
		if @article.save
			redirect_to admin_article_path(@board.title, @article)
		else
			render :action => "new"
		end
	end

	def update
		@article = @board.articles.find params[:id]
		if @article.update_attributes params[:article]
			redirect_to admin_article_path(@board.title, @article)
		else
			render :action => "edit"
		end
	end

	def destroy
		@article = @board.articles.where(id: params[:id]).first
		@article.destroy
		redirect_to admin_articles_path(@board.title)
	end

	private

	def find_board
		@board = BoardEngine::Board.find_by_title(params[:board_title])
	end

	# board type에 따라 다른 template을 render (AbstractController::Rendering#_process_options)
	def _process_options(options)
		options[:prefixes] << "board_engine/admin/articles/type_#{@board.board_type}"
	end
end

app/controllers/board_engine/admin/boards_controller.rb
# encoding: utf-8

class BoardEngine::Admin::BoardsController < BoardEngine::Admin::AdminsController
	def index
		@boards = BoardEngine::Board.all
	end
end

app/controllers/board_engine/admin/comments_controller.rb
# encoding: utf-8

class BoardEngine::Admin::CommentsController < BoardEngine::Admin::AdminsController
	def index
		@comments = BoardEngine::Comment.order("created_at DESC").page(params[:page]).per(15)
	end

	def destroy
		@comment = BoardEngine::Comment.find params[:id]
		@comment.destroy
		redirect_to request.referer || admin_comments_path
	end
end

app/controllers/board_engine/application_controller.rb
module BoardEngine
  class ApplicationController < ActionController::Base
  end
end

app/controllers/board_engine/articles_controller.rb
#encoding: utf-8

class BoardEngine::ArticlesController < ApplicationController
	before_filter :is_from_engine
	before_filter :find_board
	before_filter :require_user, :only => [:new, :edit, :create, :update, :destroy]
	before_filter(:only => [:update, :destroy]) do |c|
		@article = BoardEngine::Article.find params[:id]
		c.send(:require_owner, @article)
	end

	def index
		@articles = @board.articles.order("created_at DESC").page(params[:page]).per(15)
	end

	def show
		@article = BoardEngine::Article.find params[:id]
	end

	def new
		@article = BoardEngine::Article.new
		@article.board_id = @board.id
	end

	def edit
		@article = @board.articles.find params[:id]
	end

	def create
		@article = @board.articles.build params[:article]
		@article.user_id = current_user.id
		if @article.save
			redirect_to article_path(@board.title, @article)
		else
			render :action => "new"
		end
	end

	def update
		@article = @board.articles.find params[:id]
		if @article.update_attributes params[:article]
			redirect_to article_path(@board.title, @article)
		else
			render :action => "edit"
		end
	end

	def destroy
		@article = @board.articles.where(id: params[:id]).first
		@article.destroy
		redirect_to articles_path(@board.title)
	end


	private

	def find_board
		@board = BoardEngine::Board.find_by_title(params[:board_title])
	end

	def is_from_engine
		@is_from_engine = true
	end

	# customize template path (AbstractController::Rendering#_process_options)
	def _process_options(options)
		options[:prefixes] << "board_engine/#{@board.title.pluralize}" #main app에서 view customize용
		options[:prefixes] << "board_engine/articles/type_#{@board.board_type}" #board_engine에서 board_type별로 template render
	end
end

app/controllers/board_engine/comments_controller.rb
# encoding: utf-8

class BoardEngine::CommentsController < ApplicationController
	before_filter :is_from_engine
	before_filter :require_user
	before_filter(:only => :destroy) do |c|
		@comment = BoardEngine::Comment.find params[:id]
		c.send(:require_owner, @comment)
	end

  def create
  	@comment = BoardEngine::Comment.new params[:comment]
  	@comment.user_id = current_user.id

    if @comment.save
    	redirect_to article_path(@comment.commentable.board.title, @comment.commentable), notice: '댓글을 저장했습니다.'
    else
    	redirect_to article_path(@comment.commentable.board.title, @comment.commentable), alert: '댓글을 저장하지 못했습니다.'
    end
  end
  
  def destroy
    @comment.destroy
    article = @comment.commentable
    redirect_to article_path(article.board.title, article), :notice => "댓글을 삭제했습니다."
  end


	private

	def is_from_engine
		@is_from_engine = true
	end

end

app/helpers/board_engine/application_helper.rb
module BoardEngine
  module ApplicationHelper
  end
end

app/views/board_engine/admin/articles/new.html.erb
<%= simple_form_for [:admin, @article], :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/admin/articles/type_1/_form.html.erb
  <fieldset>
    <legend>글 등록/수정</legend>
    
    <%= f.input :title %>
    <%= f.input :body, :input_html => {:class => 'cleditor'}  %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', [:admin, :articles], :class => 'btn' %>
    </div>
  </fieldset>

app/views/board_engine/admin/articles/type_1/edit.html.erb
<%= simple_form_for [:admin, @article], :url => admin_article_path(@board.title, @article), :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/admin/articles/type_1/index.html.erb
<h1><%= t @board.title %></h1>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>제목</th>
      <th>조회수</th>
      <th>등록일</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= link_to article.title, admin_article_path(@board.title, article) %></td>
        <td><%= link_to article.hit %></td>
        <td><%= l article.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

<%= link_to '새로운 글 등록', [:new, :admin, :article], :class => 'btn btn-primary' %>

app/views/board_engine/admin/articles/type_1/new.html.erb
<%= simple_form_for [:admin, @article], :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/admin/articles/type_1/show.html.erb
<h1><%= @board.title %></h1>

<p>
	<b>제목</b>
	<%= @article.title %>
</p>

<p>
	<b>본문</b>
	<%= raw @article.body %>
</p>

<div class="form-actions">
  <%= link_to '목록으로', [:admin, :articles], :class => 'btn'  %>
  <%= link_to '수정', edit_admin_article_path(@board.title, @article), :class => 'btn' %>
  <%= link_to '삭제', admin_article_path(@board.title, @article), :method => 'delete', :confirm => '정말로 삭제하시겠습니까?', :class => 'btn btn-danger' %>
</div>


<%= render :partial => "/board_engine/admin/comments/comment_list", :locals => {:object => @article} %>

app/views/board_engine/admin/articles/type_2/_form.html.erb
  <fieldset>
    <legend>글 등록/수정</legend>
    <%= f.input :title %>
    <%= f.input :attached_picture, as: 'file' %>
    <%= f.input :body, :input_html => {:class => 'cleditor'}  %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', [:admin, :articles], :class => 'btn' %>
    </div>
  </fieldset>

app/views/board_engine/admin/articles/type_2/edit.html.erb
<%= simple_form_for [:admin, @article], :url => admin_article_path(@board.title, @article), :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/admin/articles/type_2/index.html.erb
<h1><%= t @board.title %></h1>

<ul class="thumbnails">
  <% @articles.each do |article| %>
    <li class="span3">
      <div class="thumbnail">
        <%= image_tag article.attached_picture.url %>
        <h5><%= link_to truncate(article.title, :length => 20), admin_article_path(@board.title, article) %></h5>
        <p><%= truncate strip_tags(article.body), :length => 150 %></p>
      </div>
    </li>
  <% end %>
</ul>  

<%= paginate @articles %>

<%= link_to '새로운 글 등록', [:new, :admin, :article], :class => 'btn btn-primary' %>

app/views/board_engine/admin/articles/type_2/new.html.erb
<%= simple_form_for [:admin, @article], :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/admin/articles/type_2/show.html.erb
<h1><%= @board.title %></h1>

<p>
	<b>제목</b>
	<%= @article.title %>
</p>

<p>
	<b>본문</b>
	<br />
	<%= image_tag @article.attached_picture.url %>
	<%= raw @article.body %>
</p>

<div class="form-actions">
  <%= link_to '목록으로', [:admin, :articles], :class => 'btn'  %>
  <%= link_to '수정', edit_admin_article_path(@board.title, @article), :class => 'btn' %>
  <%= link_to '삭제', admin_article_path(@board.title, @article), :method => 'delete', :confirm => '정말로 삭제하시겠습니까?', :class => 'btn btn-danger' %>
</div>

<%= render :partial => "/board_engine/admin/comments/comment_list", :locals => {:object => @article} %>

app/views/board_engine/admin/boards/index.html.erb
<h2>게시판 목록</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>게시판 이름</th>
      <th>등록일</th>
    </tr>
  </thead>
  <tbody>
    <% @boards.each do |board| %>
      <tr>
        <td><%= board.id %></td>
        <td><%= link_to t(board.title), admin_articles_path(board.title) %></td>
        <td><%= l board.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/board_engine/admin/comments/_comment_list.html.erb
<div class="comments_wrapper">
  <% if object.comments.count > 0 %>
    <div class="comment_list_area">
      <% object.comments.order("created_at DESC").each_with_index do |comment, i| %>
        <div class="comment_box <%= 'first' if i == 0 %>">
          <div class="delete"><%= link_to '삭제', admin_comment_path(comment), :method => "delete", :confirm => "정말로 삭제하시겠습니까?" %></div>
          <div class="user_detail">
            <p><%= comment.user.try(:nick_name) %></p>
            <span><%= l comment.created_at.to_date %></span>
          </div>
          <div class="body">
            <%= simple_format comment.body %>
          </div>
          <div class="clear"></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/board_engine/admin/comments/index.html.erb
<h2>게시판 목록</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>게시판 이름</th>
      <th>내용</th>
      <th>등록일</th>
      <th>게시물 링크</th>
      <td>삭제</td>
    </tr>
  </thead>
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.id %></td>
        <td><%= t comment.commentable.board.title %></td>
        <td><%= simple_format comment.body %></td>
        <td><%= l comment.created_at %></td>
        <td><%= link_to '게시물 보기', admin_article_path(comment.commentable.board.title, comment.commentable), :class => 'btn btn-mini' %></td>
        <td><%= link_to '삭제', admin_comment_path(comment), method: 'delete', confirm: '정말로 삭제하시겠습니까?', :class => 'btn btn-mini btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @comments %>

app/views/board_engine/articles/index.html.erb
<h2><%= t @board.title %></h2>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>제목</th>
      <th>조회수</th>
      <th>등록일</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= link_to article.title, article_path(@board.title, article) %></td>
        <td><%= link_to article.hit %></td>
        <td><%= l article.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

<%= link_to '새로운 글 등록', [:new, :article], :class => 'btn btn-primary' %>

app/views/board_engine/articles/type_1/_form.html.erb
  <fieldset>
    <legend>글 등록/수정</legend>
    <%= f.input :title %>
    <%= f.input :body, :input_html => {:class => 'cleditor'}  %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', [:admin, :articles], :class => 'btn' %>
    </div>
  </fieldset>

app/views/board_engine/articles/type_1/edit.html.erb
<%= simple_form_for @article, :url => article_path(@board.title, @article), :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/articles/type_1/index.html.erb
<div class="page-header">
  <h2><%= t @board.title %></h2>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>제목</th>
      <th>조회수</th>
      <th>등록일</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= link_to article.title, article_path(@board.title, article) %></td>
        <td><%= article.hit %></td>
        <td><%= l article.created_at.to_date %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= paginate @articles %>

<%= link_to '새로운 글 등록', [:new, :article], :class => 'btn btn-primary' %>

app/views/board_engine/articles/type_1/new.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/articles/type_1/show.html.erb
<div class="page-header">
  <h2><%= t @board.title %></h2>
</div>

<p>
	<b>제목</b>
	<%= @article.title %>
</p>

<p>
	<b>본문</b>
	<%= raw @article.body %>
</p>

<div class="form-actions">
  <%= link_to '목록으로', :articles, :class => 'btn'  %>

  <% if owner_of?(@article) %>
	  <%= link_to '수정', edit_article_path(@board.title, @article), :class => 'btn' %>
	  <%= link_to '삭제', article_path(@board.title, @article), :method => 'delete', :confirm => '정말로 삭제하시겠습니까?', :class => 'btn btn-danger' %>
	<% end %>
</div>

<%= render :partial => "/board_engine/comments/comment_area", :locals => {:object => @article} %>

app/views/board_engine/articles/type_2/_form.html.erb
  <fieldset>
    <legend>글 등록/수정</legend>
    <%= f.input :title %>
    <%= f.input :attached_picture, as: 'file' %>
    <%= f.input :body, :input_html => {:class => 'cleditor'}  %>
    <div class="form-actions">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to 'Cancel', :articles, :class => 'btn' %>
    </div>
  </fieldset>

app/views/board_engine/articles/type_2/edit.html.erb
<%= simple_form_for @article, :url => article_path(@board.title, @article), :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/articles/type_2/index.html.erb
<div class="page-header">
  <h2><%= t @board.title %></h2>
</div>

<ul class="thumbnails">
  <% @articles.each do |article| %>
    <li class="span3">
      <div class="thumbnail">
        <%= image_tag article.attached_picture.url %>
        <h5><%= link_to truncate(article.title, :length => 20), article_path(@board.title, article) %></h5>
        <p><%= truncate strip_tags(article.body), :length => 150 %></p>
      </div>
    </li>
  <% end %>
</ul>  

<%= paginate @articles %>

<%= link_to '새로운 글 등록', [:new, :article], :class => 'btn btn-primary' %>

app/views/board_engine/articles/type_2/new.html.erb
<%= simple_form_for @article, :html => { :class => 'form-horizontal' } do |f| %>
	<%= render 'form', f: f %>
<% end %>

app/views/board_engine/articles/type_2/show.html.erb
<div class="page-header">
  <h2><%= t @board.title %></h2>
</div>

<p>
	<b>제목</b>
	<%= @article.title %>
</p>

<p>
	<b>본문</b>
	<br />
	<%= image_tag @article.attached_picture.url %>
	<%= raw @article.body %>
</p>

<div class="form-actions">
  <%= link_to '목록으로', :articles, :class => 'btn'  %>
  <% if owner_of?(@article) %>
	  <%= link_to '수정', edit_article_path(@board.title, @article), :class => 'btn' %>
	  <%= link_to '삭제', article_path(@board.title, @article), :method => 'delete', :confirm => '정말로 삭제하시겠습니까?', :class => 'btn btn-danger' %>
	<% end %>
</div>

<%= render :partial => "/board_engine/comments/comment_area", :locals => {:object => @article} %>

app/views/board_engine/comments/_comment_area.html.erb
<div class="comments_wrapper">
  <h4>댓글 남기기</h4>
  <% if current_user %>
    <div class="new_comment_area">
      <% new_comment = BoardEngine::Comment.new(:commentable_type => object.class.model_name, :commentable_id => object.id) %>
      <%= form_for new_comment, :html => { :class => 'form-inline' } do |f| %>
        <%= f.hidden_field :commentable_type %>
        <%= f.hidden_field :commentable_id %>
        <%= f.text_area :body, :style => "width: 570px; height: 40px;" %>
        <%= f.submit '댓글 등록', :class => 'btn btn-primary btn-large', :style => 'margin: 7px;' %>
      <% end %>
    </div>
    
  <% else %>
    <p id="comment_login_required">
      로그인 후 댓글을 남길 수 있습니다. <<%= link_to '로그인', login_path(:redirect_to => request.path) %>>
    </p>
  <% end %>

  <% if object.comments.count > 0 %>
    <div class="comment_list_area well">
      <% object.comments.order("created_at DESC").each_with_index do |comment, i| %>
        <div class="comment_box <%= 'first' if i == 0 %>">
          <div>
            <span style="font-weight: bold;"><%= comment.user.try(:nick_name) %></span>
            <span><%= l comment.created_at.to_date %></span> 
            <% if owner_of?(comment) %>
              <span class="delete">
                <%= link_to '삭제', comment, :method => "delete", :confirm => "정말로 삭제하시겠습니까?" %>
              </span>
            <% end %>
          </div>
          <div style="margin-left: 10px; margin-top: 5px;">
            <%= simple_format comment.body %>
          </div>
          <hr >
          <div class="clear"></div>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/board_engine/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BoardEngine</title>
  <%= stylesheet_link_tag    "board_engine/application", :media => "all" %>
  <%= javascript_include_tag "board_engine/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>